# Generated by Django 5.1.1 on 2024-11-06 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meetname", models.CharField(max_length=64)),
                ("user", models.CharField(max_length=32)),
                ("meetdate", models.DateField()),
                ("check_time", models.TimeField(max_length=32)),
                ("status", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100, unique=True)),
                ("pwd", models.CharField(max_length=256)),
                ("role", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Meetinglist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("starttime", models.TimeField()),
                ("endtime", models.TimeField()),
                ("title", models.CharField(max_length=64)),
                ("outpeople", models.CharField(max_length=64)),
                ("status", models.CharField(max_length=64)),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meet.dept"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="qiandao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=32)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meet.meetinglist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("user", models.CharField(max_length=100, unique=True)),
                ("pwd", models.CharField(max_length=256)),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meet.dept"
                    ),
                ),
            ],
        ),
    ]
